### ISSUE TITLE
Is there a way to create a subscription endpoint without the ID appended to the url?

### ISSUE THREAD

**Issue by earlyriser** [superfeedr/rack-superfeedr#25]
I'm using a line like
Rack::Superfeedr.subscribe("http://push-pub.appspot.com/feed", 9999, {retrieve: true })
to create a subscription, and I get an endpoint like 
http://test.com/mycontroler/feed/9999/

Is there a way to have the endpoint like http://test.com/mycontroler/feed/ ? I tried false instead an id number in the subscribe parameters and I got a random id appended to the url. This is because all my subscriptions have the same endpoint.

**Comment by julien51** [comment]
Hum... you mean, you'd like the *same* endpoint for all your feeds? That's usually considered bad practice.

Could you clarify?

**Comment by earlyriser** [comment]
Ah, I didn't know it was a bad practice. The thing is that http://test.com/mycontroler/feed/ is just processing the calls from superfeedr and I didn't see the value in having a specific endpoint for each feed because I'm doing some validation when the endpoint is called.

I assumed this was correct because when I was creating subscriptions from SF dashboard, all of them subscription could share the same endpoint.

Is there a way this generalization could be a good practice, like grouping similar feeds and asign an endpoint for each of this groups, or in general is a bad idea?

Then I think I'm just going to to change the route.

Do you have planned to create a demo for Rails as the one you have for Sinatra?

Thanks!

**Comment by julien51** [comment]
Having different callback urls should help process notifications faster (without even looking at the body at first)... It's also very helpful to debug things as most HTTP logs will include the path of the requests (and not the body).

I can't think of any benefit of grouping under the same callback... and if you need grouping, you could always do so using prefixes, such as `group-feed` or `group/feed`.

We do not have any Rails demo, but I think it should be fairly easy to create one if you really need one.

**Comment by earlyriser** [comment]
It would be great if you could provide a Rails demo. I have it working, for
the subscribe/unsubscribe, but I cannot figure how the on_notification part
should be done. Thanks!

**Comment by julien51** [comment]
Sorry for the delay. I'll tackle that later this week.
In the meantime, you could just create a simple controller wich listens to
the route /mycontroler/feed/ and handle POST requests :)

Thanks
On Mon, Jan 5, 2015 at 6:27 AM, earlyriser <notifications@github.com> wrote:

    It would be great if you could provide a Rails demo. I have it working,
for
    the subscribe/unsubscribe, but I cannot figure how the on_notification
part
    should be done. Thanks!

    On Sun, Jan 4, 2015 at 4:39 PM, Julien Genestoux <
notifications@github.com>
    wrote:

    > Having different callback urls should help process notifications
faster
    > (without even looking at the body at first)... It's also very helpful
to
    > debug things as most HTTP logs will include the path of the requests
(and
    > not the body).
    >
    > I can't think of any benefit of grouping under the same callback...
and if
    > you need grouping, you could always do so using prefixes, such as
    > group-feed or group/feed.
    >
    > We do not have any Rails demo, but I think it should be fairly easy to
    > create one if you really need one.
    >
    > —
    > Reply to this email directly or view it on GitHub
    > <
https://github.com/superfeedr/rack-superfeedr/issues/25#issuecomment-68650309

**Comment by earlyriser** [comment]
Yeah, that's exactly how it's working now :)

**Comment by julien51** [comment]
Good to know! Closing the issue :)
