### ISSUE TITLE
Replay count parameter sent to API

### ISSUE THREAD

**Issue by shwanton** [superfeedr/rack-superfeedr#28]
I'm doing some debugging using the [replay](https://github.com/superfeedr/rack-superfeedr/blob/master/lib/rack-superfeedr.rb#L176 ) [endpoint](http://documentation.superfeedr.com/subscribers.html#replaying-notifications) from the [Rails Engine](https://github.com/superfeedr/superfeedr-engine/blob/master/lib/superfeedr_engine/engine.rb#L69).

I noticed that the 'count' parameter is not supported in the rack implementation like it is for [retrieve](https://github.com/superfeedr/rack-superfeedr/blob/master/lib/rack-superfeedr.rb#L133).

Is there a chance this can get added? Thanks!

**Comment by julien51** [comment]
Sorry for the delay! You're right. We need to add this. However, were quite late on a bunch of things, so if you have the time to just submit a PR, that would be lovely!
